// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqGoGRieeFMObtqE6eSjLE_eySIt9z69w',
    appId: '1:961372017988:web:c3edc59db2399f6e9d3311',
    messagingSenderId: '961372017988',
    projectId: 'dsa-tracker-flutter',
    authDomain: 'dsa-tracker-flutter.firebaseapp.com',
    storageBucket: 'dsa-tracker-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHnmERF3ZsjKmfBUURoVuZ79OiycVImk8',
    appId: '1:961372017988:android:d5903daa505b9ac99d3311',
    messagingSenderId: '961372017988',
    projectId: 'dsa-tracker-flutter',
    storageBucket: 'dsa-tracker-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1xXxAmXtmU0zQBk2pIFH94TT9NaBq9bI',
    appId: '1:961372017988:ios:5bb4ca2de5103ef59d3311',
    messagingSenderId: '961372017988',
    projectId: 'dsa-tracker-flutter',
    storageBucket: 'dsa-tracker-flutter.appspot.com',
    iosBundleId: 'com.example.dsaTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1xXxAmXtmU0zQBk2pIFH94TT9NaBq9bI',
    appId: '1:961372017988:ios:5bb4ca2de5103ef59d3311',
    messagingSenderId: '961372017988',
    projectId: 'dsa-tracker-flutter',
    storageBucket: 'dsa-tracker-flutter.appspot.com',
    iosBundleId: 'com.example.dsaTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqGoGRieeFMObtqE6eSjLE_eySIt9z69w',
    appId: '1:961372017988:web:6ba72be9e69494709d3311',
    messagingSenderId: '961372017988',
    projectId: 'dsa-tracker-flutter',
    authDomain: 'dsa-tracker-flutter.firebaseapp.com',
    storageBucket: 'dsa-tracker-flutter.appspot.com',
  );

}